### ISSUE TITLE
Error: spawn pod ENOENT

### ISSUE THREAD

**Issue by cdanyl** [nrwl/nx-react-native#13]
* Running `npx nx g @nrwl/react-native:app <app-name>` gives error `Error: spawn pod ENOENT`

```
 npx nx g @nrwl/react-native:app mobile                                                                                                                                          ✔  36s  08:36:39 
    chmod 509 apps/mobile/android/gradlew
✔ Packages installed successfully.
✔ Packages installed successfully.
    Running `pod install` from "apps/mobile/ios"
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn pod ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pod',
  path: 'pod',
  spawnargs: [ 'install' ]
}
```
```
Platform: OSX (Big Sur)
Nx --version: 10.4.1
@nrwl/react-native: 10.4.0
```

**Comment by jaysoo** [comment]
Hi @cdanyl, can you run the following?

```
sudo gem install cocoapods
```

Or try this if you dont' want to run with `sudo`.

```
gem install cocoapods --user-install
```

Now you should be able to run `pod install` from the ios folder.

**Comment by jaysoo** [comment]
This error message will be more clear in the next version `10.4.1`.
