### ISSUE TITLE
creating a component with --js gives an error

### ISSUE THREAD

**Issue by rborn** [nrwl/nx-react-native#71]
Hi, 

I'm trying to make a component inside a library and adding ` --js` will lead to an error.
Without this argument all works fine

```
Executing task: nx generate @nrwl/react-native:component --name=em-test --project=shared-ui --directory=libs/shared-ui/src --export --js --no-interactive <

TypeError: Cannot read property 'toString' of null
    at DevkitTreeFromAngularDevkitTree.read (/Users/dan/Work/tmp/nxtest/node_modules/@nrwl/devkit/src/utils/invoke-nx-generator.js:129:39)
    at addExportsToBarrel (/Users/dan/Work/tmp/nxtest/node_modules/@nrwl/react-native/src/generators/component/component.js:39:34)
    at /Users/dan/Work/tmp/nxtest/node_modules/@nrwl/react-native/src/generators/component/component.js:13:9
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dan/Work/tmp/nxtest/node_modules/tslib/tslib.js:114:62)
Cannot read property 'toString' of null
The terminal process "/bin/bash '-l', '-c', '/Users/dan/Work/tmp/nxtest/node_modules/.bin/nx generate @nrwl/react-native:component --name=em-test --project=shared-ui --directory=libs/shared-ui/src --export --js --no-interactive', 'nx generate @nrwl/react-native:component --name=em-test --project=shared-ui --directory=libs/shared-ui/src --export --js --no-interactive'" terminated with exit code: 1.

```

Creating it in an app works fine , both with and without --directory (of course without the --project argument)

Any idea? 
Thank you 🤗

**Comment by jaysoo** [comment]
We'll take a look, thanks for reporting.

**Comment by xiongemi** [comment]
@rborn when creating a component using `--js` and `--export` options, it will expect the barrel `index` to be a js file as well. So you might need to change the index file under shared-ui library's src folder to be `index.js`.

**Comment by rborn** [comment]
@xiongemi It seems to work indeed, thank you for clarifying this. Maybe a documentation note should be done about this (or I didn't see it?) 
Thanks 🥰
