### ISSUE TITLE
Unable to resolve module error for new react native project 

### ISSUE THREAD

**Issue by socialchair-June** [nrwl/nx-react-native#97]
steps to reproduce- (mac)
create a new react native application and run
npx create-nx-workspace --preset=react-native
npx nx run socialchair-app:run-ios

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Unable to resolve module ./apps/socialchair-app/src/main from /Users/bob/learn/monorepo/checko/packages/socialchairapp/.: <br><br>None of these files exist:<br> &nbsp;* apps/socialchair-app/src/main(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)<br> &nbsp;* apps/socialchair-app/src/main/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)<br> &nbsp; &nbsp;at ModuleResolver.resolveDependency (/Users/bob/learn/monorepo/checko/packages/socialchairapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)<br> &nbsp; &nbsp;at DependencyGraph.resolveDependency (/Users/bob/learn/monorepo/checko/packages/socialchairapp/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)<br> &nbsp; &nbsp;at /Users/bob/learn/monorepo/checko/packages/socialchairapp/node_modules/metro/src/lib/transformHelpers.js:129:24<br> &nbsp; &nbsp;at Server._resolveRelativePath (/Users/bob/learn/monorepo/checko/packages/socialchairapp/node_modules/metro/src/Server.js:1072:12)<br> &nbsp; &nbsp;at async Server.requestProcessor [as _processBundleRequest] (/Users/bob/learn/monorepo/checko/packages/socialchairapp/node_modules/metro/src/Server.js:428:37)<br> &nbsp; &nbsp;at async Server._processRequest (/Users/bob/learn/monorepo/checko/packages/socialchairapp/node_modules/metro/src/Server.js:380:9)</pre>
</body>
</html>

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0

**Comment by socialchair-June** [comment]
restarting machine and created a new project solved the problem. iam guessing there was some old *^%^^ running interfering with this project.
